services:
  api-1:
    build:
      context: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_DB=rinha-db
      - DB_USER=postgres
      - DB_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy

  api-2:
    build:
      context: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_DB=rinha-db
      - DB_USER=postgres
      - DB_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy
  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:9999"

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rinha-db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt

